### ISSUE TITLE
Workflow Content lifecycle: needs review status and dashboard

### ISSUE THREAD

**Issue by davidsiddall** [localgovdrupal/localgov_workflows#3]
### User story

**As a:** Product Owner,
**I want:** A review date and needs review status for content to be enabled by default when I enable localgov_workflows
**So that:** there is a mechanism to keep content up to date and quality assured

### Notes

Content lifecycle refers to functionality to ensure that content is always up to date and relevant to end users.

### Acceptance tests

We want a way for an Editor [editor] to ensure that content is regularly reviewed, updated on a timely basis, and removed when no longer useful to the end user.

To achieve this, there must be a field for all pages called review date. By default, a council can choose a specific policy for all content to be reviewed. This period could be 12 months, for example. In this instance, every page that is created or updated will automatically have the review date applied to it.

A Contributor [contributor], Author [author], or Editor [editor] must also have the option to choose a different review date to their liking, whenever they edit. They can choose a specific date or timeframe eg. 3 months | 6 months | 1 year | 18 months | 2 years | 3 years

When the review date for content passes, it automatically has a status applied to it of “needs review”.

An Editor [editor] must be able to see a view that shows all pages that need reviewing. From that view, they can decide what to do with content in review.

### Tasks

- [x] Create configuration (programatically) for **2 date fields** across all content types with workflow enabled. Two fields: last review date, next review date, plus a check box to indicate that this content has been reviewed.
- [x] Configure global default review date (for example 12 months) with option to change to other timeframes, probably on an admin form
- [x] Ensure permissions allow appropriate roles to set review dates
- [x] Create 'needs review' dashboard and set permissions to view it. Possibly cleanest to have a separate list for content with a review date in the past. 
- [x] Write update hooks to add new config to existing installs.
- [x] Add some custom form_alter (or equivalent) to process the checkbox and set date fields accordingly. 
- [x] Write cron job to update content that has past the sell by date and set to state to 'needs review'.
- [x] Write tests.
- [x] Confirm that a Contributor [contributor], Author [author], or Editor [editor] can choose a different review date to their liking, whenever they edit.

**Comment by stephen-cox** [comment]
Code for this is on the [feature/3-review-date](https://github.com/localgovdrupal/localgov_workflows/tree/feature/3-review-date) branch.

As it stands it needs:
- [x] Coding standards fixes
- [x] Needs review dashboard
- [x] Tests

**Comment by finnlewis** [comment]
I'll try to take a look at this today.

**Comment by finnlewis** [comment]
Just noting the following from the original post above: 

> A Contributor [contributor], Author [author], or Editor [editor] must also have the option to choose a different review date to their liking, whenever they edit.

**Comment by finnlewis** [comment]
@davidsiddall - something that is not explicit in the requirements above is whether this whole needs review functionality should be enforced as part of localgov_workflows or should be optional. 
Actually, thinking about it, a council might have their own workflows in place but still want this review date functionality, which might point towards building this as a separate module rather than bundling it in with the rest of localgov_workflows.

**Comment by finnlewis** [comment]
Discussing with @davidsiddall  - the ability to set a specific date for review (eg 31/12/2021) is potentially important.

**Comment by stephen-cox** [comment]
> Actually, thinking about it, a council might have their own workflows in place but still want this review date functionality, which might point towards building this as a separate module rather than bundling it in with the rest of localgov_workflows.

As it stands this has requirements on LocalGov Workflows and Scheduled Transitions. Splitting it out into it's own module would be possible, but would require quite a bit of work to ensure the settings it pulls from these two modules are configurable if they aren't installed.

**Comment by stephen-cox** [comment]
@davidsiddall @willguv This is ready for some basic testing on the test site: https://test.localgovdrupal.org/.

There are likely to be some bugs and I'm working on writing tests for it, but some feedback on the UX and how the review process works would be appreciated.

Along with a review status widget in the side bar on a node edit page, there is a needs review content listing (https://test.localgovdrupal.org/admin/content/localgov_review) and an admin page to set the default review time (https://test.localgovdrupal.org/admin/config/workflow/localgov-workflows).

I'll be at the workflow working group meeting tomorrow so can demonstrate then is that's useful.

**Comment by stephen-cox** [comment]
The PR for this is ready for review #18 

I've made a few tweaks since we discussed this at the working group meeting on Wednesday. This has all been deployed to the testing site for people to check functionality: https://test.localgovdrupal.org/
